async def generate_topics_ai(prompt: str):
    """Generate topics using an AI service (placeholder)."""
    # Replace with actual AI SDK call (e.g., Vercel AI SDK)
    return [{"id": 1, "title": f"AI Topic: {prompt}", "description": "Generated by AI"}]